theme_color:    "#e8a675"
permalink:      pretty
url:            https://hanarecafe.com # hostname & protocol for this site
thumbnail_path: /assets/images/logo-512.png
instagram_url:  https://www.instagram.com/explore/locations/1104298032977143/hanare/
facebook_url:   https://www.facebook.com/%E5%B3%B6%E3%81%AE%E3%83%91%E3%83%B3%E5%AE%B6-hanare-1104298032977143/
include:
  - _headers
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - webpack
  - webpack.config.js
  - yarn.lock
plugins:
  - jekyll-polyglot
  - jekyll-sitemap

# jekyll-polyglot
languages:
  - ja
  - en
  - ko
default_lang: ja
exclude_from_localization:
  - assets
  - atom.xml
  - LICENSE
  - README.md
  - sw.js
  - 404.html
parallel_localization: true
