- title: パン製造販売
  fa_icon: "hockey-puck"
  description: |
    水産業の盛んな答志島には、さまざまな海産物が溢れており、それをパンにも使用しています。
    島外から来られた方にも印象に残るメニューを工夫しています。
- title: 店内カフェ
  fa_icon: "coffee"
  description: |
    小さな店舗ですが八席のカフェスペースを設け、パンを店内でも食べることができるようにしました。
    コーヒーやソフトアイスなど喫茶メニューも揃えています。
- title: パン移動販売
  fa_icon: "truck"
  description: |
    島の反対側の答志地区まで車でのパン移動販売をしています。
    また、市営定期船にパンを積み込み、各島（坂手島・菅島・神島）へパンを配達しています。
- title: スペシャルオーダーサービス
  fa_icon: "plus"
  description: |
    お弁当、お料理、誕生日ケーキならぬバースディタルト等のスペシャルオーダーを承り可能です。
